language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_install:
  - composer self-update
  - composer validate

install:
  - composer install --prefer-dist

script:
  - bin/phpmd src text codesize,unusedcode,naming,design
  - bin/phpcs --standard=PSR2 src
  - bin/phploc --log-csv build/logs/phploc.csv src
  - bin/pdepend --jdepend-xml=build/logs/jdepend.xml --jdepend-chart=build/pdepend/dependencies.svg --overview-pyramid=build/pdepend/overview-pyramid.svg src

matrix:
  allow_failures:
    - branches:
        except:
          - master
          - stable
          - development
