%YAML 1.2
---
language: php
sudo: false
env:
  global:
    secure: "EKu7/YeziJdJV9KpJxcK+tUcgjdqrgO0CpzmJ8eOGd0/HUS2X1eOrSbFjhgT83A/nLjLV15IQq0xCnokDLtfa3n9yjxJhnTqq32ocT8SqbbS29sUjj5ppdgnupKaudqx2qnTbuz5MizaStoPjx0HUsPXp0VJrCy7i//H5O2vl+c="

php:
  - 5.3
  - 5.4
  - 5.5

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer validate
  - config github-oauth.github.com $GITHUB_TOKEN

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phpcs --standard=PSR2 src -p
...
