language: php

php:
  - 5.3
  - 5.4

before_script:
  - composer self-update
  - composer --dev install

script: bin/phpunit tests/unit/

matrix:
  allow_failures:
    - branches:
        except:
          - master
          - stable
          - PreRelease
